module.exports = 
{
    DB_USER : 'DB_USER',
    DB_PASSWORD : 'DB_PASSWORD',
    SPOTIFY_API_CLIENT_ID : 'SPOTIFY_API_CLIENT_ID',
    SPOTIFY_API_CLIENT_SECRET : 'SPOTIFY_API_CLIENT_SECRET',
    BASE_URL : 'BASE_URL'
}